#!/bin/bash
scripts/build && \
    ssh pi@raspberrypi.local "sudo systemctl stop loop-drop"; \
    scp target/armv7-unknown-linux-gnueabihf/release/loop-drop pi@raspberrypi.local:loop-drop && \
    ssh pi@raspberrypi.local -t "RUST_BACKTRACE=full ./loop-drop"
    #ssh pi@raspberrypi.local -t "./loop-drop"
